package io.clab.mpf.shop.common.repository;


import io.clab.mpf.shop.business.repository.base.IBusBaseMapper;
import io.clab.mpf.shop.common.entity.LogisticsCompany;

import com.baomidou.mybatisplus.mapper.BaseMapper;

public interface LogisticsCompanyMapper extends IBusBaseMapper<LogisticsCompany> , BaseMapper<LogisticsCompany>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_company
     *
     * @mbggenerated
     */
    int insertSelective(LogisticsCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_company
     *
     * @mbggenerated
     */
    LogisticsCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogisticsCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogisticsCompany record);
}