package io.clab.mpf.shop.common.repository;


import io.clab.mpf.shop.business.repository.base.IBusBaseMapper;
import io.clab.mpf.shop.common.entity.LogisticsMsg;

import com.baomidou.mybatisplus.mapper.BaseMapper;

public interface LogisticsMsgMapper extends IBusBaseMapper<LogisticsMsg> , BaseMapper<LogisticsMsg>{
	
	
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    int insertSelective(LogisticsMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    LogisticsMsg selectByPrimaryKey(Long id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    LogisticsMsg selectByLogisticNo(String logisticNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogisticsMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogisticsMsg record);
}