package io.clab.mpf.shop.business.entity.order;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@ApiModel(value="订单")
public class Order implements Serializable {

	@ApiModelProperty("订单id")
    private Long orderId;

	@ApiModelProperty("订单号")
    private String orderNumber;
	
	@ApiModelProperty("订单类型（1：普通订单;2：团购）")
    private Integer orderType;

	@ApiModelProperty("商家ID")
    private Long merchantsId;

	@ApiModelProperty("用户id")
    private Long userId;

	@ApiModelProperty("订单总金额")
    private Long totalAmount;

	@ApiModelProperty("实付金额")
    private Long paidAmount;

	@ApiModelProperty("优惠金额")
    private Long discountAmount;

	@ApiModelProperty("收货id")
    private Long receiveId;

	@ApiModelProperty("开具发票标志 0 否 1 是")
    private Byte invoiceTag;

	@ApiModelProperty("支付方式id（1 积分兑换）")
    private Integer paymentId;

	@ApiModelProperty("在线支付流水号")
    private String paymentSeq;

	@ApiModelProperty("订单状态 1.待支付； 2 待发货；3 待收货；4 交易成功；5 交易关闭；6 退货退款")
    private Integer orderState;

	@ApiModelProperty("发货时间")
    private Date sendTime;

	@ApiModelProperty("备注说明")
    private String comment;

	@ApiModelProperty("删除 1是 2否")
    private Byte delState;

	@ApiModelProperty("下单时间")
    private Date createTime;

	@ApiModelProperty("更新时间")
    private Date updateTime;
	
	@ApiModelProperty("订单单品")
	private List<OrderDetails> OrderDetails;

    private static final long serialVersionUID = 1L;


    public Long getOrderId() {
        return orderId;
    }


    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }


    public String getOrderNumber() {
        return orderNumber;
    }


    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }


    public Long getMerchantsId() {
        return merchantsId;
    }


    public void setMerchantsId(Long merchantsId) {
        this.merchantsId = merchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_amount
     *
     * @return the value of t_order.total_amount
     *
     * @mbggenerated
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_amount
     *
     * @param totalAmount the value for t_order.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.paid_amount
     *
     * @return the value of t_order.paid_amount
     *
     * @mbggenerated
     */
    public Long getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.paid_amount
     *
     * @param paidAmount the value for t_order.paid_amount
     *
     * @mbggenerated
     */
    public void setPaidAmount(Long paidAmount) {
        this.paidAmount = paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.discount_amount
     *
     * @return the value of t_order.discount_amount
     *
     * @mbggenerated
     */
    public Long getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.discount_amount
     *
     * @param discountAmount the value for t_order.discount_amount
     *
     * @mbggenerated
     */
    public void setDiscountAmount(Long discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receive_id
     *
     * @return the value of t_order.receive_id
     *
     * @mbggenerated
     */
    public Long getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receive_id
     *
     * @param receiveId the value for t_order.receive_id
     *
     * @mbggenerated
     */
    public void setReceiveId(Long receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.invoice_tag
     *
     * @return the value of t_order.invoice_tag
     *
     * @mbggenerated
     */
    public Byte getInvoiceTag() {
        return invoiceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.invoice_tag
     *
     * @param invoiceTag the value for t_order.invoice_tag
     *
     * @mbggenerated
     */
    public void setInvoiceTag(Byte invoiceTag) {
        this.invoiceTag = invoiceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payment_id
     *
     * @return the value of t_order.payment_id
     *
     * @mbggenerated
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payment_id
     *
     * @param paymentId the value for t_order.payment_id
     *
     * @mbggenerated
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payment_seq
     *
     * @return the value of t_order.payment_seq
     *
     * @mbggenerated
     */
    public String getPaymentSeq() {
        return paymentSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payment_seq
     *
     * @param paymentSeq the value for t_order.payment_seq
     *
     * @mbggenerated
     */
    public void setPaymentSeq(String paymentSeq) {
        this.paymentSeq = paymentSeq == null ? null : paymentSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_state
     *
     * @return the value of t_order.order_state
     *
     * @mbggenerated
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_state
     *
     * @param orderState the value for t_order.order_state
     *
     * @mbggenerated
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }
    
    

    public Integer getOrderType() {
		return orderType;
	}


	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.send_time
     *
     * @return the value of t_order.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.send_time
     *
     * @param sendTime the value for t_order.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.comment
     *
     * @return the value of t_order.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.comment
     *
     * @param comment the value for t_order.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.del_state
     *
     * @return the value of t_order.del_state
     *
     * @mbggenerated
     */
    public Byte getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.del_state
     *
     * @param delState the value for t_order.del_state
     *
     * @mbggenerated
     */
    public void setDelState(Byte delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_time
     *
     * @return the value of t_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_time
     *
     * @param updateTime the value for t_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    

    public List<OrderDetails> getOrderDetails() {
		return OrderDetails;
	}


	public void setOrderDetails(List<OrderDetails> orderDetails) {
		OrderDetails = orderDetails;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Order other = (Order) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOrderNumber() == null ? other.getOrderNumber() == null : this.getOrderNumber().equals(other.getOrderNumber()))
            && (this.getMerchantsId() == null ? other.getMerchantsId() == null : this.getMerchantsId().equals(other.getMerchantsId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTotalAmount() == null ? other.getTotalAmount() == null : this.getTotalAmount().equals(other.getTotalAmount()))
            && (this.getPaidAmount() == null ? other.getPaidAmount() == null : this.getPaidAmount().equals(other.getPaidAmount()))
            && (this.getDiscountAmount() == null ? other.getDiscountAmount() == null : this.getDiscountAmount().equals(other.getDiscountAmount()))
            && (this.getReceiveId() == null ? other.getReceiveId() == null : this.getReceiveId().equals(other.getReceiveId()))
            && (this.getInvoiceTag() == null ? other.getInvoiceTag() == null : this.getInvoiceTag().equals(other.getInvoiceTag()))
            && (this.getPaymentId() == null ? other.getPaymentId() == null : this.getPaymentId().equals(other.getPaymentId()))
            && (this.getPaymentSeq() == null ? other.getPaymentSeq() == null : this.getPaymentSeq().equals(other.getPaymentSeq()))
            && (this.getOrderState() == null ? other.getOrderState() == null : this.getOrderState().equals(other.getOrderState()))
            && (this.getSendTime() == null ? other.getSendTime() == null : this.getSendTime().equals(other.getSendTime()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getDelState() == null ? other.getDelState() == null : this.getDelState().equals(other.getDelState()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderNumber() == null) ? 0 : getOrderNumber().hashCode());
        result = prime * result + ((getMerchantsId() == null) ? 0 : getMerchantsId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTotalAmount() == null) ? 0 : getTotalAmount().hashCode());
        result = prime * result + ((getPaidAmount() == null) ? 0 : getPaidAmount().hashCode());
        result = prime * result + ((getDiscountAmount() == null) ? 0 : getDiscountAmount().hashCode());
        result = prime * result + ((getReceiveId() == null) ? 0 : getReceiveId().hashCode());
        result = prime * result + ((getInvoiceTag() == null) ? 0 : getInvoiceTag().hashCode());
        result = prime * result + ((getPaymentId() == null) ? 0 : getPaymentId().hashCode());
        result = prime * result + ((getPaymentSeq() == null) ? 0 : getPaymentSeq().hashCode());
        result = prime * result + ((getOrderState() == null) ? 0 : getOrderState().hashCode());
        result = prime * result + ((getSendTime() == null) ? 0 : getSendTime().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getDelState() == null) ? 0 : getDelState().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", merchantsId=").append(merchantsId);
        sb.append(", userId=").append(userId);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", paidAmount=").append(paidAmount);
        sb.append(", discountAmount=").append(discountAmount);
        sb.append(", receiveId=").append(receiveId);
        sb.append(", invoiceTag=").append(invoiceTag);
        sb.append(", paymentId=").append(paymentId);
        sb.append(", paymentSeq=").append(paymentSeq);
        sb.append(", orderState=").append(orderState);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", comment=").append(comment);
        sb.append(", delState=").append(delState);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}