package io.clab.mpf.shop.business.entity.order;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

@ApiModel(value="订单单品")
public class OrderDetails implements Serializable {


	@ApiModelProperty("订单详情id")
    private Long orderDetailsId;

	@ApiModelProperty("订单id")
    private Long orderId;

	@ApiModelProperty("订单号")
    private String orderNumber;

	@ApiModelProperty("商品id")
    private Integer goodsId;

	@ApiModelProperty("商品规格价格id")
    private Integer priceId;

	@ApiModelProperty("规格大小")
    private String specSize;

	@ApiModelProperty("规格重量")
    private String specWeight;

	@ApiModelProperty("规格颜色")
    private String specColour;

	@ApiModelProperty("商品名称")
    private String goodsName;

	@ApiModelProperty("商品规格价格")
    private Long unitPrice;

	@ApiModelProperty("个数")
    private Integer num;

	@ApiModelProperty("订单单品总价")
    private Long detailsAmount;

	@ApiModelProperty("商品主图")
    private String image;

	@ApiModelProperty("创建时间")
    private Date createTime;

	@ApiModelProperty("更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.order_details_id
     *
     * @return the value of t_order_details.order_details_id
     *
     * @mbggenerated
     */
    public Long getOrderDetailsId() {
        return orderDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.order_details_id
     *
     * @param orderDetailsId the value for t_order_details.order_details_id
     *
     * @mbggenerated
     */
    public void setOrderDetailsId(Long orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.order_id
     *
     * @return the value of t_order_details.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.order_id
     *
     * @param orderId the value for t_order_details.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.order_number
     *
     * @return the value of t_order_details.order_number
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.order_number
     *
     * @param orderNumber the value for t_order_details.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.goods_id
     *
     * @return the value of t_order_details.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.goods_id
     *
     * @param goodsId the value for t_order_details.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.price_id
     *
     * @return the value of t_order_details.price_id
     *
     * @mbggenerated
     */
    public Integer getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.price_id
     *
     * @param priceId the value for t_order_details.price_id
     *
     * @mbggenerated
     */
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.spec_size
     *
     * @return the value of t_order_details.spec_size
     *
     * @mbggenerated
     */
    public String getSpecSize() {
        return specSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.spec_size
     *
     * @param specSize the value for t_order_details.spec_size
     *
     * @mbggenerated
     */
    public void setSpecSize(String specSize) {
        this.specSize = specSize == null ? null : specSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.spec_weight
     *
     * @return the value of t_order_details.spec_weight
     *
     * @mbggenerated
     */
    public String getSpecWeight() {
        return specWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.spec_weight
     *
     * @param specWeight the value for t_order_details.spec_weight
     *
     * @mbggenerated
     */
    public void setSpecWeight(String specWeight) {
        this.specWeight = specWeight == null ? null : specWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.spec_colour
     *
     * @return the value of t_order_details.spec_colour
     *
     * @mbggenerated
     */
    public String getSpecColour() {
        return specColour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.spec_colour
     *
     * @param specColour the value for t_order_details.spec_colour
     *
     * @mbggenerated
     */
    public void setSpecColour(String specColour) {
        this.specColour = specColour == null ? null : specColour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.goods_name
     *
     * @return the value of t_order_details.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.goods_name
     *
     * @param goodsName the value for t_order_details.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.unit_price
     *
     * @return the value of t_order_details.unit_price
     *
     * @mbggenerated
     */
    public Long getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.unit_price
     *
     * @param unitPrice the value for t_order_details.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.num
     *
     * @return the value of t_order_details.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.num
     *
     * @param num the value for t_order_details.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.details_amount
     *
     * @return the value of t_order_details.details_amount
     *
     * @mbggenerated
     */
    public Long getDetailsAmount() {
        return detailsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.details_amount
     *
     * @param detailsAmount the value for t_order_details.details_amount
     *
     * @mbggenerated
     */
    public void setDetailsAmount(Long detailsAmount) {
        this.detailsAmount = detailsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.image
     *
     * @return the value of t_order_details.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.image
     *
     * @param image the value for t_order_details.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.create_time
     *
     * @return the value of t_order_details.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.create_time
     *
     * @param createTime the value for t_order_details.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.update_time
     *
     * @return the value of t_order_details.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.update_time
     *
     * @param updateTime the value for t_order_details.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderDetails other = (OrderDetails) that;
        return (this.getOrderDetailsId() == null ? other.getOrderDetailsId() == null : this.getOrderDetailsId().equals(other.getOrderDetailsId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOrderNumber() == null ? other.getOrderNumber() == null : this.getOrderNumber().equals(other.getOrderNumber()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getPriceId() == null ? other.getPriceId() == null : this.getPriceId().equals(other.getPriceId()))
            && (this.getSpecSize() == null ? other.getSpecSize() == null : this.getSpecSize().equals(other.getSpecSize()))
            && (this.getSpecWeight() == null ? other.getSpecWeight() == null : this.getSpecWeight().equals(other.getSpecWeight()))
            && (this.getSpecColour() == null ? other.getSpecColour() == null : this.getSpecColour().equals(other.getSpecColour()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getUnitPrice() == null ? other.getUnitPrice() == null : this.getUnitPrice().equals(other.getUnitPrice()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getDetailsAmount() == null ? other.getDetailsAmount() == null : this.getDetailsAmount().equals(other.getDetailsAmount()))
            && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderDetailsId() == null) ? 0 : getOrderDetailsId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderNumber() == null) ? 0 : getOrderNumber().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getPriceId() == null) ? 0 : getPriceId().hashCode());
        result = prime * result + ((getSpecSize() == null) ? 0 : getSpecSize().hashCode());
        result = prime * result + ((getSpecWeight() == null) ? 0 : getSpecWeight().hashCode());
        result = prime * result + ((getSpecColour() == null) ? 0 : getSpecColour().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getUnitPrice() == null) ? 0 : getUnitPrice().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getDetailsAmount() == null) ? 0 : getDetailsAmount().hashCode());
        result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDetailsId=").append(orderDetailsId);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", priceId=").append(priceId);
        sb.append(", specSize=").append(specSize);
        sb.append(", specWeight=").append(specWeight);
        sb.append(", specColour=").append(specColour);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", num=").append(num);
        sb.append(", detailsAmount=").append(detailsAmount);
        sb.append(", image=").append(image);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}