package io.clab.mpf.shop.business.entity.uuser;

import java.io.Serializable;
import java.util.Date;

public class TagAuthorization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_authorization.aut_id
     *
     * @mbggenerated
     */
    private Long autId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_authorization.uuser_id
     *
     * @mbggenerated
     */
    private Long uuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_authorization.tag_id
     *
     * @mbggenerated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_authorization.authorization_flag
     *
     * @mbggenerated
     */
    private Byte authorizationFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_authorization.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_authorization.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_authorization.aut_id
     *
     * @return the value of t_tag_authorization.aut_id
     *
     * @mbggenerated
     */
    public Long getAutId() {
        return autId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_authorization.aut_id
     *
     * @param autId the value for t_tag_authorization.aut_id
     *
     * @mbggenerated
     */
    public void setAutId(Long autId) {
        this.autId = autId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_authorization.uuser_id
     *
     * @return the value of t_tag_authorization.uuser_id
     *
     * @mbggenerated
     */
    public Long getUuserId() {
        return uuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_authorization.uuser_id
     *
     * @param uuserId the value for t_tag_authorization.uuser_id
     *
     * @mbggenerated
     */
    public void setUuserId(Long uuserId) {
        this.uuserId = uuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_authorization.tag_id
     *
     * @return the value of t_tag_authorization.tag_id
     *
     * @mbggenerated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_authorization.tag_id
     *
     * @param tagId the value for t_tag_authorization.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_authorization.authorization_flag
     *
     * @return the value of t_tag_authorization.authorization_flag
     *
     * @mbggenerated
     */
    public Byte getAuthorizationFlag() {
        return authorizationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_authorization.authorization_flag
     *
     * @param authorizationFlag the value for t_tag_authorization.authorization_flag
     *
     * @mbggenerated
     */
    public void setAuthorizationFlag(Byte authorizationFlag) {
        this.authorizationFlag = authorizationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_authorization.create_time
     *
     * @return the value of t_tag_authorization.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_authorization.create_time
     *
     * @param createTime the value for t_tag_authorization.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_authorization.update_time
     *
     * @return the value of t_tag_authorization.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_authorization.update_time
     *
     * @param updateTime the value for t_tag_authorization.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TagAuthorization other = (TagAuthorization) that;
        return (this.getAutId() == null ? other.getAutId() == null : this.getAutId().equals(other.getAutId()))
            && (this.getUuserId() == null ? other.getUuserId() == null : this.getUuserId().equals(other.getUuserId()))
            && (this.getTagId() == null ? other.getTagId() == null : this.getTagId().equals(other.getTagId()))
            && (this.getAuthorizationFlag() == null ? other.getAuthorizationFlag() == null : this.getAuthorizationFlag().equals(other.getAuthorizationFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAutId() == null) ? 0 : getAutId().hashCode());
        result = prime * result + ((getUuserId() == null) ? 0 : getUuserId().hashCode());
        result = prime * result + ((getTagId() == null) ? 0 : getTagId().hashCode());
        result = prime * result + ((getAuthorizationFlag() == null) ? 0 : getAuthorizationFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", autId=").append(autId);
        sb.append(", uuserId=").append(uuserId);
        sb.append(", tagId=").append(tagId);
        sb.append(", authorizationFlag=").append(authorizationFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}