package io.clab.mpf.shop.business.repository.uuser;

import io.clab.mpf.shop.business.entity.uuser.TagAuthorization;

public interface TagAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long autId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    int insert(TagAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    int insertSelective(TagAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    TagAuthorization selectByPrimaryKey(Long autId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TagAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_authorization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TagAuthorization record);
}