package io.clab.mpf.shop.common.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

@ApiModel(value="物流信息")
public class LogisticsMsg implements Serializable {
	
	@ApiModelProperty("id")
    private Long id;

	@ApiModelProperty("物流单号")
    private String logisticNo;

	@ApiModelProperty("物流状态：2-在途中,3-签收,4-问题件")
    private String state;

	@ApiModelProperty("物流信息")
    private String content;

	@ApiModelProperty("数据获取标识")
    private String getLogo;

	@ApiModelProperty("创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics_msg.id
     *
     * @return the value of t_logistics_msg.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics_msg.id
     *
     * @param id the value for t_logistics_msg.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics_msg.Logistic_no
     *
     * @return the value of t_logistics_msg.Logistic_no
     *
     * @mbggenerated
     */
    public String getLogisticNo() {
        return logisticNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics_msg.Logistic_no
     *
     * @param logisticNo the value for t_logistics_msg.Logistic_no
     *
     * @mbggenerated
     */
    public void setLogisticNo(String logisticNo) {
        this.logisticNo = logisticNo == null ? null : logisticNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics_msg.state
     *
     * @return the value of t_logistics_msg.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics_msg.state
     *
     * @param state the value for t_logistics_msg.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics_msg.content
     *
     * @return the value of t_logistics_msg.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics_msg.content
     *
     * @param content the value for t_logistics_msg.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics_msg.get_logo
     *
     * @return the value of t_logistics_msg.get_logo
     *
     * @mbggenerated
     */
    public String getGetLogo() {
        return getLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics_msg.get_logo
     *
     * @param getLogo the value for t_logistics_msg.get_logo
     *
     * @mbggenerated
     */
    public void setGetLogo(String getLogo) {
        this.getLogo = getLogo == null ? null : getLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics_msg.create_time
     *
     * @return the value of t_logistics_msg.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics_msg.create_time
     *
     * @param createTime the value for t_logistics_msg.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LogisticsMsg other = (LogisticsMsg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLogisticNo() == null ? other.getLogisticNo() == null : this.getLogisticNo().equals(other.getLogisticNo()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getGetLogo() == null ? other.getGetLogo() == null : this.getGetLogo().equals(other.getGetLogo()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLogisticNo() == null) ? 0 : getLogisticNo().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getGetLogo() == null) ? 0 : getGetLogo().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logistics_msg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", logisticNo=").append(logisticNo);
        sb.append(", state=").append(state);
        sb.append(", content=").append(content);
        sb.append(", getLogo=").append(getLogo);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}