package io.clab.mpf.shop.business.entity.goods;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

@ApiModel(value="商品")
public class Goods implements Serializable {

	@ApiModelProperty("商品id")
    private Integer goodsId;

	@ApiModelProperty("商家ID")
    private Long merchantsId;

	@ApiModelProperty("所属类别id")
    private Integer categoryId;

	@ApiModelProperty("所属品牌id")
    private Integer brandId;

	@ApiModelProperty("商品名称")
    private String goodsName;

	@ApiModelProperty("别名")
    private String nickname;

	@ApiModelProperty("商品货号")
    private String goodsNo;

	@ApiModelProperty("顺序")
    private Integer sequence;

	@ApiModelProperty("是否置顶（1：是；0：否）")
    private Byte topFlag;

	@ApiModelProperty("商品主图")
    private String primaryImage;

	@ApiModelProperty("商品图")
    private String image;

	@ApiModelProperty("简要描述")
    private String simpleDescribe;

	@ApiModelProperty("详细描述")
    private String detailDescribe;

	@ApiModelProperty("产地")
    private String attributeProductionPlace;

	@ApiModelProperty("主要材质")
    private String attributeMainMaterial;

	@ApiModelProperty("产品功能")
    private String attributeGoodsFunction;

	@ApiModelProperty("适用季节(1:春季；2：夏季；3：秋季；4：冬季；0：通用)")
    private Integer attributeApplySeason;

	@ApiModelProperty("年龄段(1:0-10;2:11-18;3:18-30;4:31-50;5:51-100)")
    private Integer attributeAgeGroup;

	@ApiModelProperty("商品适合性别（1：男；0：女）")
    private Integer attributeSex;

	@ApiModelProperty("审核状态（1：审核通过，2：审核不通过，0：待审核）")
    private Integer checkState;

	@ApiModelProperty("上架标志 1 已上架 0 未上架")
    private Integer isMarketable;

	@ApiModelProperty("推荐 1是 2否")
    private Integer recommend;

	@ApiModelProperty("删除 1是 2否")
    private Integer delState;

	@ApiModelProperty("创建时间")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

	@ApiModelProperty("更新时间")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

	@ApiModelProperty("创建者id")
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_id
     *
     * @return the value of t_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_id
     *
     * @param goodsId the value for t_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.merchants_id
     *
     * @return the value of t_goods.merchants_id
     *
     * @mbggenerated
     */
    public Long getMerchantsId() {
        return merchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.merchants_id
     *
     * @param merchantsId the value for t_goods.merchants_id
     *
     * @mbggenerated
     */
    public void setMerchantsId(Long merchantsId) {
        this.merchantsId = merchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.category_id
     *
     * @return the value of t_goods.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.category_id
     *
     * @param categoryId the value for t_goods.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.brand_id
     *
     * @return the value of t_goods.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.brand_id
     *
     * @param brandId the value for t_goods.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.nickname
     *
     * @return the value of t_goods.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.nickname
     *
     * @param nickname the value for t_goods.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_no
     *
     * @return the value of t_goods.goods_no
     *
     * @mbggenerated
     */
    public String getGoodsNo() {
        return goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_no
     *
     * @param goodsNo the value for t_goods.goods_no
     *
     * @mbggenerated
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo == null ? null : goodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.sequence
     *
     * @return the value of t_goods.sequence
     *
     * @mbggenerated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.sequence
     *
     * @param sequence the value for t_goods.sequence
     *
     * @mbggenerated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.top_flag
     *
     * @return the value of t_goods.top_flag
     *
     * @mbggenerated
     */
    public Byte getTopFlag() {
        return topFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.top_flag
     *
     * @param topFlag the value for t_goods.top_flag
     *
     * @mbggenerated
     */
    public void setTopFlag(Byte topFlag) {
        this.topFlag = topFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.primary_image
     *
     * @return the value of t_goods.primary_image
     *
     * @mbggenerated
     */
    public String getPrimaryImage() {
        return primaryImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.primary_image
     *
     * @param primaryImage the value for t_goods.primary_image
     *
     * @mbggenerated
     */
    public void setPrimaryImage(String primaryImage) {
        this.primaryImage = primaryImage == null ? null : primaryImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.image
     *
     * @return the value of t_goods.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.image
     *
     * @param image the value for t_goods.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.simple_describe
     *
     * @return the value of t_goods.simple_describe
     *
     * @mbggenerated
     */
    public String getSimpleDescribe() {
        return simpleDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.simple_describe
     *
     * @param simpleDescribe the value for t_goods.simple_describe
     *
     * @mbggenerated
     */
    public void setSimpleDescribe(String simpleDescribe) {
        this.simpleDescribe = simpleDescribe == null ? null : simpleDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.detail_describe
     *
     * @return the value of t_goods.detail_describe
     *
     * @mbggenerated
     */
    public String getDetailDescribe() {
        return detailDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.detail_describe
     *
     * @param detailDescribe the value for t_goods.detail_describe
     *
     * @mbggenerated
     */
    public void setDetailDescribe(String detailDescribe) {
        this.detailDescribe = detailDescribe == null ? null : detailDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.attribute_production_place
     *
     * @return the value of t_goods.attribute_production_place
     *
     * @mbggenerated
     */
    public String getAttributeProductionPlace() {
        return attributeProductionPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.attribute_production_place
     *
     * @param attributeProductionPlace the value for t_goods.attribute_production_place
     *
     * @mbggenerated
     */
    public void setAttributeProductionPlace(String attributeProductionPlace) {
        this.attributeProductionPlace = attributeProductionPlace == null ? null : attributeProductionPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.attribute_main_material
     *
     * @return the value of t_goods.attribute_main_material
     *
     * @mbggenerated
     */
    public String getAttributeMainMaterial() {
        return attributeMainMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.attribute_main_material
     *
     * @param attributeMainMaterial the value for t_goods.attribute_main_material
     *
     * @mbggenerated
     */
    public void setAttributeMainMaterial(String attributeMainMaterial) {
        this.attributeMainMaterial = attributeMainMaterial == null ? null : attributeMainMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.attribute_goods_function
     *
     * @return the value of t_goods.attribute_goods_function
     *
     * @mbggenerated
     */
    public String getAttributeGoodsFunction() {
        return attributeGoodsFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.attribute_goods_function
     *
     * @param attributeGoodsFunction the value for t_goods.attribute_goods_function
     *
     * @mbggenerated
     */
    public void setAttributeGoodsFunction(String attributeGoodsFunction) {
        this.attributeGoodsFunction = attributeGoodsFunction == null ? null : attributeGoodsFunction.trim();
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_time
     *
     * @return the value of t_goods.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_time
     *
     * @param createTime the value for t_goods.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.update_time
     *
     * @return the value of t_goods.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.update_time
     *
     * @param updateTime the value for t_goods.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.admin_id
     *
     * @return the value of t_goods.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.admin_id
     *
     * @param adminId the value for t_goods.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    public Integer getAttributeApplySeason() {
		return attributeApplySeason;
	}

	public void setAttributeApplySeason(Integer attributeApplySeason) {
		this.attributeApplySeason = attributeApplySeason;
	}

	public Integer getAttributeAgeGroup() {
		return attributeAgeGroup;
	}

	public void setAttributeAgeGroup(Integer attributeAgeGroup) {
		this.attributeAgeGroup = attributeAgeGroup;
	}

	public Integer getAttributeSex() {
		return attributeSex;
	}

	public void setAttributeSex(Integer attributeSex) {
		this.attributeSex = attributeSex;
	}

	public Integer getCheckState() {
		return checkState;
	}

	public void setCheckState(Integer checkState) {
		this.checkState = checkState;
	}

	public Integer getIsMarketable() {
		return isMarketable;
	}

	public void setIsMarketable(Integer isMarketable) {
		this.isMarketable = isMarketable;
	}

	public Integer getRecommend() {
		return recommend;
	}

	public void setRecommend(Integer recommend) {
		this.recommend = recommend;
	}

	public Integer getDelState() {
		return delState;
	}

	public void setDelState(Integer delState) {
		this.delState = delState;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Goods other = (Goods) that;
        return (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getMerchantsId() == null ? other.getMerchantsId() == null : this.getMerchantsId().equals(other.getMerchantsId()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getBrandId() == null ? other.getBrandId() == null : this.getBrandId().equals(other.getBrandId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getGoodsNo() == null ? other.getGoodsNo() == null : this.getGoodsNo().equals(other.getGoodsNo()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getTopFlag() == null ? other.getTopFlag() == null : this.getTopFlag().equals(other.getTopFlag()))
            && (this.getPrimaryImage() == null ? other.getPrimaryImage() == null : this.getPrimaryImage().equals(other.getPrimaryImage()))
            && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage()))
            && (this.getSimpleDescribe() == null ? other.getSimpleDescribe() == null : this.getSimpleDescribe().equals(other.getSimpleDescribe()))
            && (this.getDetailDescribe() == null ? other.getDetailDescribe() == null : this.getDetailDescribe().equals(other.getDetailDescribe()))
            && (this.getAttributeProductionPlace() == null ? other.getAttributeProductionPlace() == null : this.getAttributeProductionPlace().equals(other.getAttributeProductionPlace()))
            && (this.getAttributeMainMaterial() == null ? other.getAttributeMainMaterial() == null : this.getAttributeMainMaterial().equals(other.getAttributeMainMaterial()))
            && (this.getAttributeGoodsFunction() == null ? other.getAttributeGoodsFunction() == null : this.getAttributeGoodsFunction().equals(other.getAttributeGoodsFunction()))
            && (this.getAttributeApplySeason() == null ? other.getAttributeApplySeason() == null : this.getAttributeApplySeason().equals(other.getAttributeApplySeason()))
            && (this.getAttributeAgeGroup() == null ? other.getAttributeAgeGroup() == null : this.getAttributeAgeGroup().equals(other.getAttributeAgeGroup()))
            && (this.getAttributeSex() == null ? other.getAttributeSex() == null : this.getAttributeSex().equals(other.getAttributeSex()))
            && (this.getCheckState() == null ? other.getCheckState() == null : this.getCheckState().equals(other.getCheckState()))
            && (this.getIsMarketable() == null ? other.getIsMarketable() == null : this.getIsMarketable().equals(other.getIsMarketable()))
            && (this.getRecommend() == null ? other.getRecommend() == null : this.getRecommend().equals(other.getRecommend()))
            && (this.getDelState() == null ? other.getDelState() == null : this.getDelState().equals(other.getDelState()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAdminId() == null ? other.getAdminId() == null : this.getAdminId().equals(other.getAdminId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getMerchantsId() == null) ? 0 : getMerchantsId().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getGoodsNo() == null) ? 0 : getGoodsNo().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getTopFlag() == null) ? 0 : getTopFlag().hashCode());
        result = prime * result + ((getPrimaryImage() == null) ? 0 : getPrimaryImage().hashCode());
        result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
        result = prime * result + ((getSimpleDescribe() == null) ? 0 : getSimpleDescribe().hashCode());
        result = prime * result + ((getDetailDescribe() == null) ? 0 : getDetailDescribe().hashCode());
        result = prime * result + ((getAttributeProductionPlace() == null) ? 0 : getAttributeProductionPlace().hashCode());
        result = prime * result + ((getAttributeMainMaterial() == null) ? 0 : getAttributeMainMaterial().hashCode());
        result = prime * result + ((getAttributeGoodsFunction() == null) ? 0 : getAttributeGoodsFunction().hashCode());
        result = prime * result + ((getAttributeApplySeason() == null) ? 0 : getAttributeApplySeason().hashCode());
        result = prime * result + ((getAttributeAgeGroup() == null) ? 0 : getAttributeAgeGroup().hashCode());
        result = prime * result + ((getAttributeSex() == null) ? 0 : getAttributeSex().hashCode());
        result = prime * result + ((getCheckState() == null) ? 0 : getCheckState().hashCode());
        result = prime * result + ((getIsMarketable() == null) ? 0 : getIsMarketable().hashCode());
        result = prime * result + ((getRecommend() == null) ? 0 : getRecommend().hashCode());
        result = prime * result + ((getDelState() == null) ? 0 : getDelState().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAdminId() == null) ? 0 : getAdminId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsId=").append(goodsId);
        sb.append(", merchantsId=").append(merchantsId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", brandId=").append(brandId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", nickname=").append(nickname);
        sb.append(", goodsNo=").append(goodsNo);
        sb.append(", sequence=").append(sequence);
        sb.append(", topFlag=").append(topFlag);
        sb.append(", primaryImage=").append(primaryImage);
        sb.append(", image=").append(image);
        sb.append(", simpleDescribe=").append(simpleDescribe);
        sb.append(", detailDescribe=").append(detailDescribe);
        sb.append(", attributeProductionPlace=").append(attributeProductionPlace);
        sb.append(", attributeMainMaterial=").append(attributeMainMaterial);
        sb.append(", attributeGoodsFunction=").append(attributeGoodsFunction);
        sb.append(", attributeApplySeason=").append(attributeApplySeason);
        sb.append(", attributeAgeGroup=").append(attributeAgeGroup);
        sb.append(", attributeSex=").append(attributeSex);
        sb.append(", checkState=").append(checkState);
        sb.append(", isMarketable=").append(isMarketable);
        sb.append(", recommend=").append(recommend);
        sb.append(", delState=").append(delState);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", adminId=").append(adminId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}