package io.clab.mpf.shop.business.repository.order;

import java.util.List;

import io.clab.mpf.shop.business.entity.order.OrderDetails;
import io.clab.mpf.shop.business.repository.base.IBusBaseMapper;

import com.baomidou.mybatisplus.mapper.BaseMapper;

public interface OrderDetailsMapper extends IBusBaseMapper<OrderDetails> , BaseMapper<OrderDetails>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orderDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    OrderDetails selectByPrimaryKey(Long orderDetailsId);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderDetails record);
    
    List<OrderDetails> selectByOrderId(Long orderId);
}