package io.clab.mpf.shop.business.repository.goods;

import com.baomidou.mybatisplus.mapper.BaseMapper;

import io.clab.mpf.shop.business.entity.goods.GoodsCategory;
import io.clab.mpf.shop.business.repository.base.IBusBaseMapper;

public interface GoodsCategoryMapper extends IBusBaseMapper<GoodsCategory> , BaseMapper<GoodsCategory>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoryId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbggenerated
     */
    GoodsCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCategory record);
}