package io.clab.mpf.shop.business.repository.goods;

import io.clab.mpf.shop.business.entity.goods.Goods;
import io.clab.mpf.shop.business.entity.goods.GoodsDetail;
import io.clab.mpf.shop.business.repository.base.IBusBaseMapper;

import java.util.List;
import java.util.Map;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.baomidou.mybatisplus.plugins.pagination.Pagination;

public interface GoodsMapper extends IBusBaseMapper<Goods> , BaseMapper<Goods>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodsId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    Goods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Goods record);
    
    List<GoodsDetail> selectPageList(Pagination page,Map paramMap);
}